language: php

sudo: false

php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

matrix:
  include:
    - php: 5.3
      env: SYMFONY_VERSION='^2'
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      env: SYMFONY_VERSION='^3'
    - php: 7.1
      env: SYMFONY_VERSION='^4'
    - php: 7.2
      env: SYMFONY_VERSION='^5'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require -n --no-update symfony/browser-kit=$SYMFONY_VERSION; fi;

install:
  - composer install -n --prefer-dist

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
